### ISSUE TITLE
Linux Mint 21.3 Cinnamon - When creating a wallet Meile shuts down

### ISSUE THREAD

**Issue by Bebop125** [MathNodes/meile-gui#100]
Prompting to create wallet
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "hashlib.py", line 160, in __hash_new
 ValueError: [digital envelope routines] unsupported
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "main/meile_gui.py", line 10, in <module>
   File "main/meile_gui.py", line 6, in main
   File "kivy/app.py", line 956, in run
   File "kivy/base.py", line 574, in runTouchApp
   File "kivy/base.py", line 339, in mainloop
   File "kivy/base.py", line 383, in idle
   File "kivy/base.py", line 334, in dispatch_input
   File "kivy/base.py", line 302, in post_dispatch_input
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "kivymd/uix/button/button.py", line 1187, in on_touch_up
   File "kivymd/uix/behaviors/ripple_behavior.py", line 404, in on_touch_up
   File "kivy/uix/behaviors/button.py", line 179, in on_touch_up
   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "ui/screens.py", line 170, in wallet_restore
   File "cli/wallet.py", line 206, in create
   File "hashlib.py", line 166, in __hash_new
   File "hashlib.py", line 123, in __get_builtin_constructor
 ValueError: unsupported hash type ripemd160
[64023] Failed to execute script 'meile_gui' due to unhandled exception!

**Comment by Tkd-Alex** [comment]
1. Find the openssl directory `openssl version -d`
2. Navigate on that folder and edit the config file `nano openssl.cnf`
3. Make sure that the config file contains following lines:
 ```
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
  ```

**Comment by MathNodes** [comment]
Yes. This is what you need to do. The Debian package I created for 22.04 does this automatically and since I did not have a version out prior to ubuntu 24.04 I did not think it necessary to include this fix in that deb. I was wrong. Will patch this going forward in the Debian packages. 

⁣freQniK- Core Developer
MathNodes
www.mathnodes.com​

**Comment by Bebop125** [comment]
That worked. Thank you.
